import { sql } from "drizzle-orm";
import { check, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Users, authenticated by GitHub OAuth (ADR 0020) or by email and password
 * (ADR 0043). An account may end up with both.
 *
 * `id` is a UUIDv7 generated by PostgreSQL 18's native `uuidv7()` — time-ordered
 * primary keys, friendly to future cursor-based pagination. `github_id` is the
 * stable external identifier used to upsert on login (name/email may change).
 *
 * Both credential columns are nullable, so the check constraint below is what
 * keeps an account nobody can sign into from existing.
 */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().default(sql`uuidv7()`),
    /** Null for a password-only account. */
    githubId: text("github_id").unique(),
    name: text("name"),
    email: text("email").notNull().unique(),
    /** argon2id hash, salt and parameters included. Null for an OAuth-only account. */
    passwordHash: text("password_hash"),
    imageUrl: text("image_url"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    check(
      "users_has_credential_check",
      sql`${table.githubId} is not null or ${table.passwordHash} is not null`,
    ),
  ],
);

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
