import type { Session } from "../../../shared/db/schema/sessions.js";

/**
 * Data to create a server-side session (ADR 0016/0019). `id` is the opaque,
 * high-entropy token generated by the auth layer and stored in the httpOnly
 * cookie; `userId` references the owning user; `expiresAt` bounds its lifetime.
 */
export interface CreateSessionInput {
  id: string;
  userId: string;
  expiresAt: Date;
}

/**
 * Port for session persistence (ADR 0014, ADR 0027). Adapters implement it:
 * `createPostgresSessionRepository` (production) and an in-memory fake (tests).
 */
export interface SessionRepository {
  create(input: CreateSessionInput): Promise<Session>;
  findById(id: string): Promise<Session | null>;
  deleteById(id: string): Promise<void>;
}
