import { sql } from "drizzle-orm";
import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Users authenticated via GitHub OAuth (ADR 0020).
 *
 * `id` is a UUIDv7 generated by PostgreSQL 18's native `uuidv7()` — time-ordered
 * primary keys, friendly to future cursor-based pagination. `github_id` is the
 * stable external identifier used to upsert on login (name/email may change).
 */
export const users = pgTable("users", {
  id: uuid("id").primaryKey().default(sql`uuidv7()`),
  githubId: text("github_id").notNull().unique(),
  name: text("name"),
  email: text("email").notNull().unique(),
  imageUrl: text("image_url"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
