import type { Invite } from "../domain/invite.js";
import type { InviteResourceType, ResourceRef } from "../domain/resource.js";

/** Data to persist a new invite. The token is generated by the service. */
export interface CreateInviteInput {
  /** Opaque bearer token; unique across all invites. */
  token: string;
  resourceType: InviteResourceType;
  /** Id of the invited-to resource. Not foreign-keyed (ADR 0040). */
  resourceId: string;
  /** `users.id` of the inviter. */
  createdBy: string;
  expiresAt: Date;
}

/**
 * Port for invite persistence (ADR 0040, ADR 0027). Deliberately dumb: validity
 * (expiry, revocation) is decided by the domain, so this just loads and stores.
 * It speaks in **domain entities**, not rows — adapters map (ADR 0047). Adapters: `createPostgresInviteRepository`
 * (production) and an in-memory fake (tests).
 */
export interface InviteRepository {
  create(input: CreateInviteInput): Promise<Invite>;
  findById(id: string): Promise<Invite | null>;
  /** The invite bearing this token, whatever its state. */
  findByToken(token: string): Promise<Invite | null>;
  /** Every invite for a resource, newest first, including dead ones. */
  listForResource(ref: ResourceRef): Promise<Invite[]>;
  /** Marks the invite revoked. A no-op if it is already revoked or unknown. */
  revoke(id: string, revokedAt: Date): Promise<void>;
}
