import type {
  Invite,
  InviteResourceType,
} from "../../../shared/db/schema/invites.js";

/** Data to persist a new invite. The token is generated by the service. */
export interface CreateInviteInput {
  /** Opaque bearer token; unique across all invites. */
  token: string;
  resourceType: InviteResourceType;
  /** Id of the invited-to resource. Not foreign-keyed (ADR 0040). */
  resourceId: string;
  /** `users.id` of the inviter. */
  createdBy: string;
  expiresAt: Date;
}

export interface ResourceRef {
  resourceType: InviteResourceType;
  resourceId: string;
}

/**
 * Port for invite persistence (ADR 0040, ADR 0027). Deliberately dumb: validity
 * (expiry, revocation) is decided by the service, which owns the clock, so this
 * returns rows as they are. Adapters: `createPostgresInviteRepository`
 * (production) and an in-memory fake (tests).
 */
export interface InviteRepository {
  create(input: CreateInviteInput): Promise<Invite>;
  findById(id: string): Promise<Invite | null>;
  /** The invite bearing this token, whatever its state. */
  findByToken(token: string): Promise<Invite | null>;
  /** Every invite for a resource, newest first, including dead ones. */
  listForResource(ref: ResourceRef): Promise<Invite[]>;
  /** Marks the invite revoked. A no-op if it is already revoked or unknown. */
  revoke(id: string, revokedAt: Date): Promise<void>;
}
